name: CI

on:
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: Show Devices List
      run: xcrun instruments -s
    - name: SwiftLint
      run: brew install swiftlint && swiftlint
    - name: XCTest
      run: xcodebuild test -scheme CurrencyLayeriOS -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4'
    - name: Build # シミュレーター向け
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
